#!/bin/sh

if ! [ $# -eq 3 ]; then
	echo "Syntax: 002_zini <sw> CONFIG|DECONFIG <output-script>" >&2
	exit 8
fi
sw="$1"
verb="$2"
script="$3"

zospm=`whence zospm`
zospmdir=${zospm%/*}
zospmroot=${zospmdir%/*}

cat << EOF >${script}
#!/bin/sh
#set -x
export verb="${verb}"
export PATH=${zospmdir}:\$PATH
export sw="${sw}"
. zospmsetswenv "${sw}"

set +x
zowedir="\${ZOSPM_TGT_ZFSROOT}usr/lpp/zowe"
zoweinstancedir="\${ZWE_INSTANCE_ROOT}"
EOF

if [ $? -gt 0 ]; then
	echo "Unable to create ${sw} Update script: ${script}." >&2
	exit 16
fi
chmod u+x "${script}"

if [ "${verb}" = "CONFIG" ]; then
cat <<'EOF' >>${script}
	chkProperties "ZWE_KEYSTORE_DIRECTORY ZWE_LOGDIR ZWE_INSTANCE_ROOT"
	if [ $? -gt 0 ]; then
		echo "002_zini failed." >&2
		exit 8
	fi

	rm -rf "${ZWE_KEYSTORE_DIRECTORY}" "${ZWE_LOGDIR}" "${ZWE_INSTANCE_ROOT}"
	mkdir -p "${ZWE_KEYSTORE_DIRECTORY}" "${ZWE_LOGDIR}" "${ZWE_INSTANCE_ROOT}"
	rc=$?
	if [ $rc -gt 0 ]; then
		echo "Unable to create instance directories: ${ZWE_KEYSTORE_DIRECTORY} ${ZWE_LOGDIR} ${ZWE_INSTANCE_ROOT}"
		exit $rd
	fi
	chmod -R 770 "${ZWE_KEYSTORE_DIRECTORY}" "${ZWE_LOGDIR}" "${ZWE_INSTANCE_ROOT}" 
	if [ $rc -gt 0 ]; then
		echo "Unable to change ownership for instance directories: ${ZWE_KEYSTORE_DIRECTORY} ${ZWE_LOGDIR} ${ZWE_INSTANCE_ROOT}"
		exit $rd
	fi
	chown ${ZWE_ZOWEUSER}:${ZWE_ADMINGRP} "${ZWE_KEYSTORE_DIRECTORY}" "${ZWE_LOGDIR}" "${ZWE_INSTANCE_ROOT}" 
	if [ $rc -gt 0 ]; then
		echo "Unable to change ownership for instance directories: ${ZWE_KEYSTORE_DIRECTORY} ${ZWE_LOGDIR} ${ZWE_INSTANCE_ROOT}"
		exit $rd
	fi
EOF
else
cat <<'EOF' >>${script}
#
# Remove instance dir here ?
#
EOF
fi
exit 0  
