#!/bin/sh

if ! [ $# -eq 3 ]; then
	echo "Syntax: 004_zicfg <sw> CONFIG|DECONFIG <output-script>" >&2
	exit 8
fi
sw="$1"
verb="$2"
script="$3"

zospm=`whence zospm`
zospmdir=${zospm%/*}
zospmroot=${zospmdir%/*}

cat << EOF >${script}
#!/bin/sh
#set -x
export verb="${verb}"
export PATH=${zospmdir}:\$PATH
export sw="${sw}"
. zospmsetswenv "${sw}"

set +x
zowedir="\${ZOSPM_TGT_ZFSROOT}usr/lpp/zowe"
zoweinstancedir="\${ZWE_INSTANCE_ROOT}"
EOF

if [ $? -gt 0 ]; then
	echo "Unable to create ${sw} Update script: ${script}." >&2
	exit 16
fi
chmod u+x "${script}"

if [ "${verb}" = "CONFIG" ]; then
cat <<'EOF' >>${script}
	chkProperties "ZOSPM_JAVA_HOME ZOSPM_NODE_HOME ZWE_IPADDRESS" 
	if [ $? -gt 0 ]; then
		echo "004_zicfg failed." >&2
		exit 8
	fi
	export JAVA_HOME="${ZOSPM_JAVA_HOME}"
	export NODE_HOME="${ZOSPM_NODE_HOME}"
	export ZOWE_EXPLORER_HOST="${ZWE_IPADDRESS}"
	export ZOWE_IP_ADDRESS="${ZWE_IPADDRESS}"
	export ZOWE_ZOSMF_HOST="${ZWE_IPADDRESS}"

	"${zowedir}/bin/zowe-configure-instance.sh" -c "${zoweinstancedir}"

	cat <<NESTEOF >>"${zoweinstancedir}/instance.env"

		CATALOG_PORT="${ZWE_CATALOG_PORT}"
		DISCOVERY_PORT="${ZWE_DISCOVERY_PORT}"
		GATEWAY_PORT="${ZWE_GATEWAY_PORT}"
		JOBS_API_PORT="${ZWE_JOBS_API_PORT}"
		FILES_API_PORT="${ZWE_FILES_API_PORT}"
		JES_EXPLORER_UI_PORT="${ZWE_JES_EXPLORER_UI_PORT}"
		MVS_EXPLORER_UI_PORT="${ZWE_MVS_EXPLORER_UI_PORT}"
		USS_EXPLORER_UI_PORT="${ZWE_USS_EXPLORER_UI_PORT}"
		ZOWE_ZLUX_SERVER_HTTPS_PORT="${ZWE_ZOWE_ZLUX_SERVER_HTTPS_PORT}"
		ZOWE_ZSS_SERVER_PORT="${ZWE_ZOWE_ZSS_SERVER_PORT}"
NESTEOF
	a2e "${zoweinstancedir}/instance.env"
EOF
else
cat <<'EOF' >>${script}
EOF
fi
exit 0  
