#!/bin/sh

if ! [ $# -eq 3 ]; then
	echo "Syntax: 007_st <sw> CONFIG|DECONFIG <output-script>" >&2
	exit 8
fi
sw="$1"
verb="$2"
script="$3"

zospm=`whence zospm`
zospmdir=${zospm%/*}
zospmroot=${zospmdir%/*}

cat << EOF >${script}
#!/bin/sh
#set -x
export verb="${verb}"
export PATH=${zospmdir}:\$PATH
export sw="${sw}"
. zospmsetswenv "${sw}"

set +x
proclib="\${ZOSPM_TGT_HLQ}PROCLIB"
zoweinstancedir="\${ZWE_INSTANCE_ROOT}"
EOF

if [ $? -gt 0 ]; then
	echo "Unable to create ${sw} Update script: ${script}." >&2
	exit 16
fi
chmod u+x "${script}"

if [ "${verb}" = "CONFIG" ]; then
cat <<'EOF' >>${script}
	opercmd 'start zwesistc'
	opercmd 'start zwesvstc'
EOF
else
cat <<'EOF' >>${script}
	opercmd 'cancel zwesvstc'
	opercmd 'cancel zwesistc'
EOF
fi
exit $?

EOF
exit 0  
